### PR TITLE
Update build to .NET 6

### PR DESCRIPTION
**Pull request by tillig**
- Implicit usings.
- File-scoped namespaces.
- Added missing documentation.
- Analyzers and rulesets updated to match core Autofac, issues fixed.
- Test types unified into 'stubs' namespace since they were already shared, but oddly nested into individual fixture files.
- VS Code build support added.
- Symbols package generated as .snupkg.
- Coverage gathered with coverlet, uploaded to Codecov using the latest updater including hash validation of the uploader executable.

### CODE REVIEW

**Comment by tillig** [comment]
I think there's something up with AppVeyor artifact handling at the moment. After our build script completes, the build itself just _hangs_. It's at the stage where AppVeyor is supposed to find the .nupkg/.snupkg artifacts, but I think it's before it actually tries to upload anything to MyGet. I'll see if I can figure it out, but I figured I'd get this in here and get it started.

**Comment by tillig** [comment]
Seems to be something specifically with _this_ build. I've added the Codecov Uploader validation to core Autofac and that build doesn't hang. Maybe the difference is Windows vs. Linux builds? I did update it to the VS 2022 image, maybe VS 2019 needs to be used. I'll poke at it.

**Comment by tillig** [comment]
[I've opened a discussion at AppVeyor to find out what's up.](https://help.appveyor.com/discussions/problems/31544-windows-images-hang-at-artifact-processing)

**Comment by tillig** [comment]
The answer here is that _on Windows agents_ if you run `gpg.exe` to do the `codecov.exe` validation it starts a background agent process (`gpg-agent`) that somehow keeps the build script alive at the end. AppVeyor is waiting for the build script to complete, but since this agent process is hanging out resident, it won't let the script complete.

Adding `gpg-connect-agent.exe killagent /bye` to the script to kill the background process once the validation is done allows the build script to complete.

While this agent also appears to run when Linux `gpg` commands execute, it _doesn't_ keep Linux builds alive. That's why you don't see the same thing in the builds running on Linux agents.

**Review by alistairjevans — APPROVED** [review]
Good find on the gpg problem, that must have been a touch tricky to figure out.

**Pull request merged**
